// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: musik/musik.proto

package musik

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lagu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Judul         string                 `protobuf:"bytes,1,opt,name=judul,proto3" json:"judul,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lagu) Reset() {
	*x = Lagu{}
	mi := &file_musik_musik_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lagu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lagu) ProtoMessage() {}

func (x *Lagu) ProtoReflect() protoreflect.Message {
	mi := &file_musik_musik_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lagu.ProtoReflect.Descriptor instead.
func (*Lagu) Descriptor() ([]byte, []int) {
	return file_musik_musik_proto_rawDescGZIP(), []int{0}
}

func (x *Lagu) GetJudul() string {
	if x != nil {
		return x.Judul
	}
	return ""
}

var File_musik_musik_proto protoreflect.FileDescriptor

const file_musik_musik_proto_rawDesc = "" +
	"\n" +
	"\x11musik/musik.proto\x12\x05musik\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n" +
	"\x04Lagu\x12\x14\n" +
	"\x05judul\x18\x01 \x01(\tR\x05judul2:\n" +
	"\x05Musik\x121\n" +
	"\bInfoLagu\x12\x16.google.protobuf.Empty\x1a\v.musik.Lagu\"\x00B%Z#github.com/fuji-184/streaming/musikb\x06proto3"

var (
	file_musik_musik_proto_rawDescOnce sync.Once
	file_musik_musik_proto_rawDescData []byte
)

func file_musik_musik_proto_rawDescGZIP() []byte {
	file_musik_musik_proto_rawDescOnce.Do(func() {
		file_musik_musik_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_musik_musik_proto_rawDesc), len(file_musik_musik_proto_rawDesc)))
	})
	return file_musik_musik_proto_rawDescData
}

var file_musik_musik_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_musik_musik_proto_goTypes = []any{
	(*Lagu)(nil),          // 0: musik.Lagu
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_musik_musik_proto_depIdxs = []int32{
	1, // 0: musik.Musik.InfoLagu:input_type -> google.protobuf.Empty
	0, // 1: musik.Musik.InfoLagu:output_type -> musik.Lagu
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_musik_musik_proto_init() }
func file_musik_musik_proto_init() {
	if File_musik_musik_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_musik_musik_proto_rawDesc), len(file_musik_musik_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_musik_musik_proto_goTypes,
		DependencyIndexes: file_musik_musik_proto_depIdxs,
		MessageInfos:      file_musik_musik_proto_msgTypes,
	}.Build()
	File_musik_musik_proto = out.File
	file_musik_musik_proto_goTypes = nil
	file_musik_musik_proto_depIdxs = nil
}
