// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: proto/hello.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Isi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pesan         string                 `protobuf:"bytes,1,opt,name=pesan,proto3" json:"pesan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Isi) Reset() {
	*x = Isi{}
	mi := &file_proto_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Isi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Isi) ProtoMessage() {}

func (x *Isi) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Isi.ProtoReflect.Descriptor instead.
func (*Isi) Descriptor() ([]byte, []int) {
	return file_proto_hello_proto_rawDescGZIP(), []int{0}
}

func (x *Isi) GetPesan() string {
	if x != nil {
		return x.Pesan
	}
	return ""
}

type Hasil struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balasan       string                 `protobuf:"bytes,1,opt,name=balasan,proto3" json:"balasan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hasil) Reset() {
	*x = Hasil{}
	mi := &file_proto_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hasil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hasil) ProtoMessage() {}

func (x *Hasil) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hasil.ProtoReflect.Descriptor instead.
func (*Hasil) Descriptor() ([]byte, []int) {
	return file_proto_hello_proto_rawDescGZIP(), []int{1}
}

func (x *Hasil) GetBalasan() string {
	if x != nil {
		return x.Balasan
	}
	return ""
}

var File_proto_hello_proto protoreflect.FileDescriptor

const file_proto_hello_proto_rawDesc = "" +
	"\n" +
	"\x11proto/hello.proto\x12\x05hello\"\x1b\n" +
	"\x03Isi\x12\x14\n" +
	"\x05pesan\x18\x01 \x01(\tR\x05pesan\"!\n" +
	"\x05Hasil\x12\x18\n" +
	"\abalasan\x18\x01 \x01(\tR\abalasan2`\n" +
	"\x05Hello\x12%\n" +
	"\aMenyapa\x12\n" +
	".hello.Isi\x1a\f.hello.Hasil\"\x00\x120\n" +
	"\x10MenyapaStreaming\x12\n" +
	".hello.Isi\x1a\f.hello.Hasil\"\x000\x01B%Z#github.com/fuji-184/streaming/protob\x06proto3"

var (
	file_proto_hello_proto_rawDescOnce sync.Once
	file_proto_hello_proto_rawDescData []byte
)

func file_proto_hello_proto_rawDescGZIP() []byte {
	file_proto_hello_proto_rawDescOnce.Do(func() {
		file_proto_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hello_proto_rawDesc), len(file_proto_hello_proto_rawDesc)))
	})
	return file_proto_hello_proto_rawDescData
}

var file_proto_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_hello_proto_goTypes = []any{
	(*Isi)(nil),   // 0: hello.Isi
	(*Hasil)(nil), // 1: hello.Hasil
}
var file_proto_hello_proto_depIdxs = []int32{
	0, // 0: hello.Hello.Menyapa:input_type -> hello.Isi
	0, // 1: hello.Hello.MenyapaStreaming:input_type -> hello.Isi
	1, // 2: hello.Hello.Menyapa:output_type -> hello.Hasil
	1, // 3: hello.Hello.MenyapaStreaming:output_type -> hello.Hasil
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_hello_proto_init() }
func file_proto_hello_proto_init() {
	if File_proto_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hello_proto_rawDesc), len(file_proto_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hello_proto_goTypes,
		DependencyIndexes: file_proto_hello_proto_depIdxs,
		MessageInfos:      file_proto_hello_proto_msgTypes,
	}.Build()
	File_proto_hello_proto = out.File
	file_proto_hello_proto_goTypes = nil
	file_proto_hello_proto_depIdxs = nil
}
